name: build and deploy docker image

on:
  push:
    # branches:
      # - 'main'
  workflow_run:
    workflows:
      - 'build release artifact'
    types:
      - completed

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: retrieve build output
      uses: actions/cache/restore@v4
      with:
        path: |
          target/release/chapter-dong-dong
        key: release-build-${{ github.head_ref }}-${{ github.sha }}

    - name: test
      run: |
        ls .

    - name: build Docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: user/app:${{ github.sha }}
