name: build release artifact

on:
  push:

jobs:
  cargo_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: run cargo test
      run: |
        cargo test

  build_release_artifact:
    runs-on: ubuntu-latest
    needs: cargo_test

    steps: 
    - uses: actions/checkout@v4

    - name: build artifact
      run: |
        cargo build --release

    - name: cache build output
      uses: actions/cache@v4
      with:
        path: target/release/chapter-dong-dong
        key: release-build-${{ github.sha }}

  build_docker:
    # if: github.head_ref == 'main'
    needs: build_release_artifact

    runs-on: ubuntu-latest

    env:
      PROJECT_ID: dev-1-420822
      REGION: europe-west9
      GAR_LOCATION: europe-west9-docker.pkg.dev/dev-1-420822/internal-clim-dev/

    steps:
      - uses: actions/checkout@v4

      - name: cache build output
        uses: actions/cache/restore@v4
        with:
          path: target/release/chapter-dong-dong
          key: release-build-${{ github.sha }}

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCLOUD_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --tag ${{ env.GAR_LOCATION }}chapter-dong-dong:${{ github.sha }}
 
      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}
       
